# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DataPoc < Formula
  desc "Kafka Consumer for Protobuf"
  homepage "https://github.com/Khushbukela/sample-go-consumer"
  version "101.0.0"

  on_macos do
    url "https://github.com/khushbukela/sample-go-consumer/releases/download/101.0.0/data-poc_Darwin_all.zip"
    sha256 "22a84aec339d946c6c153f01ac087a3a58a846bd831a9a5481a1a8ea17c04e45"

    def install
      bin.install "data-poc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/101.0.0/data-poc_Linux_arm64.zip"
      sha256 "0988da9e2b3bcae6e089371385a715e12ab6ed97ba1684135f7410af3f46122c"

      def install
        bin.install "data-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/101.0.0/data-poc_Linux_x86_64.zip"
      sha256 "5e8ecc9a0dd0e1a454522a5abce9979d04f5bf323120397738db0193ac35aa06"

      def install
        bin.install "data-poc"
      end
    end
  end
end
