# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaProtobufConsumer < Formula
  desc "Kafka Consumer for Protobuf"
  homepage "https://github.com/Khushbukela/sample-go-consumer"
  version "0.0.3"

  on_macos do
    url "https://github.com/khushbukela/sample-go-consumer/releases/download/0.0.3/kafka-protobuf-consumer_Darwin_all.zip"
    sha256 "ce753a75e54534145fd4942aa2bd8c5c87c2a7e810492a859ba05c4e660c377e"

    def install
      bin.install "kafka-protobuf-consumer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/0.0.3/kafka-protobuf-consumer_Linux_arm64.zip"
      sha256 "2d7d29bf8c7689546a40262b78daad3efdc24561b0443da840d72e66fe3fbe35"

      def install
        bin.install "kafka-protobuf-consumer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/0.0.3/kafka-protobuf-consumer_Linux_x86_64.zip"
      sha256 "dbbc9258991749e693b1919743cbe008c8d1e1236cf681a1e2b3d26e454e30ed"

      def install
        bin.install "kafka-protobuf-consumer"
      end
    end
  end
end
