# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaProtobufConsoleConsumer < Formula
  desc "Kafka Consumer for Protobuf"
  homepage "https://github.com/hotstar/data-poc/tree/kafka-protobuf-console-consumer/kafka-protobuf-consumer"
  version "12.1.36"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hotstar/kafka-protobuf-console-consumer/releases/download/12.1.36/kafka-protobuf-console-consumer_Darwin_arm64-12.1.36.zip"
      sha256 "a87a3344340e6c4e56a489857b9a8bfbf7291334880af66bdd2a217f4907b7db"

      def install
        bin.install "kafka-protobuf-console-consumer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hotstar/kafka-protobuf-console-consumer/releases/download/12.1.36/kafka-protobuf-console-consumer_Darwin_x86_64-12.1.36.zip"
      sha256 "9fd98590d165d790040d8b6855dfc67068a90065d9252c5bfbb050f408150b2e"

      def install
        bin.install "kafka-protobuf-console-consumer"
      end
    end
  end
end
