# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SampleGoConsumer < Formula
  desc "Kafka Consumer for Protobuf"
  homepage "https://github.com/Khushbukela/sample-go-consumer"
  version "200.0.6"

  on_macos do
    url "https://github.com/khushbukela/sample-go-consumer/releases/download/200.0.6/sample-go-consumer_Darwin_all.zip"
    sha256 "a357ec661228d6553e95951544098e5a28d877d75c3bad21ca484284f894e1e6"

    def install
      bin.install "sample-go-consumer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/200.0.6/sample-go-consumer_Linux_arm64.zip"
      sha256 "10066b6de2be35e4ed9c81538d6e6620e3f01537445be2450585248711ce5b9c"

      def install
        bin.install "sample-go-consumer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/200.0.6/sample-go-consumer_Linux_x86_64.zip"
      sha256 "eb8e973cc8bcfc347f901b4e5e596edc4e6e68a851614d30b0cb2b8a2aced8b2"

      def install
        bin.install "sample-go-consumer"
      end
    end
  end
end
